# образ ноды
FROM node:14.15.4-stretch

# устанавливаем инит для контейнера
RUN apk add dumb-init


# создаем и устанавливаем рабочую директорию
WORKDIR /usr/src/app
# копируем файлы из локального окружения
COPY . /usr/src/app

# устанавлвиаем переменные окружения
ENV PORT=PORT
ENV POSTGRES_USER=POSTGRES_USER
ENV POSTGRES_DB=POSTGRES_DB
ENV POSTGRES_PASSWORD=POSTGRES_PASSWORD

# устанавливаем зависимости
RUN yarn 

# декларируем порт
EXPOSE 8080
# задаем команду при запуске контейнера
CMD ["dumb-init", "node", "app.js"]