# образ ноды
FROM node:14.15.4-stretch

# создаем и устанавливаем рабочую директорию
WORKDIR /usr/src/app
# копируем файлы из локального окружения
COPY . /usr/src/app

# устанавлвиаем переменные окружения
ENV PORT=PORT
ENV POSTGRES_USER=POSTGRES_USER
ENV POSTGRES_DB=POSTGRES_DB
ENV POSTGRES_PASSWORD=POSTGRES_PASSWORD
ENV SECRET=SECRET

# устанавливаем зависимости
RUN yarn 

# декларируем порт
EXPOSE 8080
# задаем команду при запуске контейнера
CMD ["node", "app.js"]